import { ThemeConfig } from "@/types"

export const themeConfigs: Record<string, ThemeConfig> = {
  mystic: {
    id: "mystic",
    label: "Mystic Commerce",
    subtitle: "Esoteric · Occult · Premium",
    emoji: "🔮",
    colors: {
      primary: "#7C3AED",
      secondary: "#A78BFA",
      accent: "#C4B5FD",
      bg: "#0A0A14",
      surface: "rgba(124,58,237,0.08)",
      text: "#EDEDF0",
      textMuted: "#8B7AB5",
      glow: "rgba(124,58,237,0.3)",
    },
  },
  luxury: {
    id: "luxury",
    label: "Luxury Catalog",
    subtitle: "Editorial · Gold · Refined",
    emoji: "✨",
    colors: {
      primary: "#D4A84B",
      secondary: "#F5F0EB",
      accent: "#8B7355",
      bg: "#0F0D0A",
      surface: "rgba(212,168,75,0.06)",
      text: "#F5F0EB",
      textMuted: "#A09080",
      glow: "rgba(212,168,75,0.2)",
    },
  },
  brutalist: {
    id: "brutalist",
    label: "Neo Brutalist",
    subtitle: "Bold · Raw · Industrial",
    emoji: "🏛️",
    colors: {
      primary: "#FFFFFF",
      secondary: "#9CA3AF",
      accent: "#4B5563",
      bg: "#030303",
      surface: "rgba(255,255,255,0.04)",
      text: "#FFFFFF",
      textMuted: "#6B7280",
      glow: "rgba(255,255,255,0.1)",
    },
  },
  streetwear: {
    id: "streetwear",
    label: "Streetwear Drop",
    subtitle: "Urban · Hype · Bold",
    emoji: "🔥",
    colors: {
      primary: "#FF2D55",
      secondary: "#FFD60A",
      accent: "#00D4FF",
      bg: "#0A0A0A",
      surface: "rgba(255,45,85,0.08)",
      text: "#FFFFFF",
      textMuted: "#9CA3AF",
      glow: "rgba(255,45,85,0.3)",
    },
  },
  agency: {
    id: "agency",
    label: "Agency Elite",
    subtitle: "Clean · Corporate · Premium",
    emoji: "⚡",
    colors: {
      primary: "#00D4FF",
      secondary: "#7000FF",
      accent: "#FFFFFF",
      bg: "#06060C",
      surface: "rgba(0,212,255,0.05)",
      text: "#EDEDF0",
      textMuted: "#6B6B8D",
      glow: "rgba(0,212,255,0.25)",
    },
  },
  local: {
    id: "local",
    label: "Local Business",
    subtitle: "Friendly · Warm · Community",
    emoji: "🌿",
    colors: {
      primary: "#34D399",
      secondary: "#FBBF24",
      accent: "#F472B6",
      bg: "#080C0A",
      surface: "rgba(52,211,153,0.06)",
      text: "#EDEDF0",
      textMuted: "#6B8B7A",
      glow: "rgba(52,211,153,0.2)",
    },
  },
}
